// backend/models/Notification.js
// New A2 functionality: persistent in-app notifications generated by domain
// events (e.g. when a diner's review receives an owner response). Produced via
// the NotificationFactory and persisted through the NotificationRepository.

const mongoose = require('mongoose');

const notificationSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    type: {
      type: String,
      enum: ['REVIEW_CREATED', 'OWNER_RESPONSE', 'REVIEW_REMOVED', 'SYSTEM'],
      required: true,
    },
    channel: { type: String, enum: ['inapp', 'email'], default: 'inapp' },
    message: { type: String, required: true, trim: true, maxlength: 500 },
    read: { type: Boolean, default: false },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Notification', notificationSchema);
